sudo: required
language: python
services:
  - docker
python:
  - "2.7"
before_install:
  - pip install pycodestyle
  - docker pull ubuntu:16.04
script:
  # Run tests on BMv2, see Dockerfile
  - docker build .
  # Run pycodestyle on all .py files in all subfolders
  - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E127,E722 {} +
