language: python
python:
- "2.7"
before_install:
- pip install pycodestyle
script:
# Run pycodestyle on all .py files in all subfolders
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E127,E722 {} +
